Repository stephenchu530/parley-app, pull requests merged in 2019-08, with the labels that each got.

#39 Day3
  src/main/java/com/parley/parley/config/WebSecurityConfig.java
  src/main/java/com/parley/parley/controllers/UserAccountController.java
  src/test/java/com/parley/parley/ParleyApplicationTests.java
Labels: help wanted

#40 fix and remove corpse code
  src/main/java/com/parley/parley/controllers/scheduleInterviewController.java
Labels: bug

#41 Fritts
  src/main/java/com/parley/parley/controllers/UserAccountController.java
  src/main/resources/static/css/general.css
  src/main/resources/templates/aboutus.html
  src/main/resources/templates/addSchedule.html
  src/main/resources/templates/error.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/login.html
  src/main/resources/templates/makeAdmin.html
  src/main/resources/templates/myprofile.html
Labels: enhancement

#42 Displayscheduledinterviews
  Interview 02 _ common_curriculum.html
  src/main/java/com/parley/parley/controllers/evaluationController.java
  src/main/resources/templates/evaluation.html
  src/main/resources/templates/fragments/scheduledInterviewsFragment.html
  src/main/resources/templates/myprofile.html
Labels: enhancement

#43 fix: removed duplicate aboutus route
  src/main/java/com/parley/parley/controllers/UserAccountController.java
Labels: bug

#44 fix: wired in add prompts page
  src/main/resources/templates/add_prompt.html
  src/main/resources/templates/fragments/header.html
Labels: enhancement

#45 Finaldaysteve
  src/main/java/com/parley/parley/controllers/PromptsController.java
  src/main/java/com/parley/parley/controllers/UserAccountController.java
  src/main/resources/templates/add_prompt.html
Labels: bug

#46 attempted timer style fix
  src/main/resources/static/css/general.css
  src/main/resources/templates/error.html
  src/main/resources/templates/fragments/loginPageHeader.html
  src/main/resources/templates/login.html
  src/main/resources/templates/logout_completed.html
Labels: bug

#47 Rob thurs
  2019-07-31 17:50:40.909steve.txt
  bin/main/static/css/general.css
  bin/main/static/css/modalOveride.css
  bin/main/static/css/slider.css
  bin/main/static/js/disableBackButton.js
  bin/main/static/js/modal.js
  bin/main/static/js/slider.js
  bin/main/templates/aboutus.html
  bin/main/templates/addSchedule.html
  bin/main/templates/add_prompt.html
  bin/main/templates/error.html
  bin/main/templates/evaluation.html
  bin/main/templates/fragments/adminheader.html
  bin/main/templates/fragments/assessments.html
  bin/main/templates/fragments/header.html
  bin/main/templates/fragments/loggedInHeader.html
  bin/main/templates/fragments/loginPageHeader.html
  bin/main/templates/fragments/scheduledInterviewsFragment.html
  bin/main/templates/login.html
  bin/main/templates/logout_completed.html
  bin/main/templates/makeAdmin.html
  bin/main/templates/myassessments.html
  bin/main/templates/myprofile.html
  src/main/java/com/parley/parley/config/S3Client.java
  src/main/java/com/parley/parley/controllers/AssessmentsController.java
  src/main/java/com/parley/parley/controllers/DummyController.java
  src/main/java/com/parley/parley/models/Assessments.java
  src/main/java/com/parley/parley/models/UserAccount.java
  src/main/resources/templates/evaluation.html
Labels: enhancement

#48 Finaldaysteve
  src/main/resources/templates/fragments/assessments.html
  src/main/resources/templates/myassessments.html
Labels: enhancement

#49 Rob thurs
  src/main/java/com/parley/parley/controllers/DummyController.java
Labels: enhancement

#50 Day4
  src/main/java/com/parley/parley/controllers/UserAccountController.java
  src/main/resources/templates/add_prompt.html
  src/main/resources/templates/fragments/header.html
Labels: enhancement

#51 Finaldaysteve
  2019-07-31 17:50:40.909steve.txt
  src/main/java/com/parley/parley/controllers/UserAccountController.java
  src/main/resources/templates/addclass.html
  src/main/resources/templates/addstudent.html
  src/main/resources/templates/editprofile.html
  src/main/resources/templates/myprofile.html
Labels: enhancement

#52 docs: added updated renders
  docs/db_schema_drawio
  docs/db_schema_render.png
  docs/parley_drawio
  docs/parley_drawio_02
  docs/parley_render.png
  docs/parley_render_02.png
Labels: documentation

#53 Fritts
  src/main/resources/static/css/general.css
  src/main/resources/templates/aboutus.html
  src/main/resources/templates/add_prompt.html
  src/main/resources/templates/error.html
  src/main/resources/templates/evaluation.html
  src/main/resources/templates/fragments/loginPageHeader.html
  src/main/resources/templates/fragments/scheduledInterviewsFragment.html
  src/main/resources/templates/login.html
  src/main/resources/templates/myprofile.html
Labels: bug

#55 fix: fixed broken aboutus page
  src/main/java/com/parley/parley/controllers/UserAccountController.java
  src/main/resources/templates/aboutus.html
Labels: bug

#56 README
  README.md
Labels: documentation

#57 git clone
  README.md
Labels: bug

#58 css: my assessments, evaluations, etc...
  src/main/resources/static/css/general.css
  src/main/resources/templates/fragments/assessments.html
  src/main/resources/templates/login.html
  src/main/resources/templates/myassessments.html
  src/main/resources/templates/myprofile.html
Labels: enhancement

#59 added acknowledgements
  README.md
Labels: documentation

#60 fix: added logic to remove interviews as it progresses
  src/main/java/com/parley/parley/controllers/AssessmentsController.java
  src/main/java/com/parley/parley/models/Schedules.java
  src/main/resources/templates/fragments/scheduledInterviewsFragment.html
Labels: bug

#61 fix: fixed problem with different files
  src/main/java/com/parley/parley/controllers/AssessmentsController.java
Labels: bug

#62 Rob thurs
  README.md
  bin/main/templates/aboutus.html
  docs/addInterview.png
  docs/grantAdmin.png
  docs/home.png
  docs/instructorHome.png
  docs/login.png
  docs/logout.png
  docs/scheduleInterview.png
  docs/studentHome.png
  docs/studentWithScheduled.png
  docs/viewAssessments.png
Labels: documentation

#63 Rob thurs
  README.md
Labels: documentation
