Repository stephenchu530/parley-app, pull requests merged in 2019-07, with the labels that each got.

#13 Student Model
  src/main/java/com/parley/parley/models/Student.java
Labels: enhancement

#16 WebSecurity Config
  src/main/java/com/parley/parley/UserDetailsServiceImplementation.java
  src/main/java/com/parley/parley/config/DynamoDBConfig.java
  src/main/java/com/parley/parley/config/WebSecurityConfig.java
  src/main/java/com/parley/parley/models/Student.java
  src/main/java/com/parley/parley/repository/StudentRepository.java
Labels: enhancement

#15 updating readme
  README.md
Labels: documentation

#18 Refactor base code to use RDS-Postgresql for authentication
  README.md
  build.gradle
  docs/db_schema_drawio
  docs/db_schema_drawio_01
  docs/db_schema_render.png
  docs/db_schema_render_01.png
  docs/parley_drawio
  docs/parley_drawio_01
  docs/parley_render.png
  docs/parley_render_01.png
  src/main/java/com/parley/parley/models/Student.java
  src/main/resources/application.properties
Labels: bug, refactor

#19 some basic scaffolding. models and html
  src/main/java/com/parley/parley/models/Assessments.java
  src/main/java/com/parley/parley/models/Schedules.java
  src/main/resources/static/images/dry-erase-home.png
  src/main/resources/templates/aboutus.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/loggedInHeader.html
  src/main/resources/templates/home.html
  src/main/resources/templates/myprofile.html
Labels: enhancement

#20 feat: added prompts model and repository
  src/main/java/com/parley/parley/models/Prompts.java
  src/main/java/com/parley/parley/repository/PromptsRepository.java
Labels: enhancement

#21 Fritts
  src/main/java/com/parley/parley/ParleyApplication.java
  src/main/java/com/parley/parley/config/DynamoDBConfig.java
  src/main/java/com/parley/parley/config/WebSecurityConfig.java
  src/main/java/com/parley/parley/controllers/InstructorController.java
  src/main/java/com/parley/parley/models/Instructor.java
  src/main/java/com/parley/parley/models/RoleType.java
  src/main/java/com/parley/parley/repository/InstructorRepository.java
  src/main/java/com/parley/parley/repository/PromptsRepository.java
  src/main/java/com/parley/parley/repository/RoleRepository.java
  src/main/resources/application.properties
  src/main/resources/templates/login.html
Labels: enhancement

#22 refactor: changed to use RDS instead of dynamoDB because things
  src/main/java/com/parley/parley/models/Assessments.java
  src/main/java/com/parley/parley/models/Prompts.java
  src/main/java/com/parley/parley/models/Schedules.java
Labels: refactor

#23 assessments and schedules repostitory
  src/main/java/com/parley/parley/repository/AssessmentsRepository.java
  src/main/java/com/parley/parley/repository/SchedulesRepository.java
Labels: enhancement

#24 chore: removed all references to dynamodb
  src/main/java/com/parley/parley/config/DynamoDBConfig.java
  src/main/resources/application.properties
Labels: refactor

#25 feat: added s3 bucket capability for 3 buckets
  src/main/java/com/parley/parley/config/S3Client.java
  src/main/resources/application.properties
Labels: enhancement

#26 changed UUID to Long
  src/main/java/com/parley/parley/models/Assessments.java
  src/main/java/com/parley/parley/models/Instructor.java
  src/main/java/com/parley/parley/models/Prompts.java
  src/main/java/com/parley/parley/models/RoleType.java
  src/main/java/com/parley/parley/models/Schedules.java
  src/main/java/com/parley/parley/repository/AssessmentsRepository.java
  src/main/java/com/parley/parley/repository/InstructorRepository.java
  src/main/java/com/parley/parley/repository/PromptsRepository.java
  src/main/java/com/parley/parley/repository/RoleRepository.java
  src/main/java/com/parley/parley/repository/SchedulesRepository.java
  src/main/java/com/parley/parley/repository/StudentRepository.java
  src/main/resources/static/images/markerAndEraser.jpg
  src/main/resources/templates/logout_completed.html
Labels: bug

#27 Fritts
  src/main/java/com/parley/parley/config/WebSecurityConfig.java
  src/main/java/com/parley/parley/controllers/InstructorController.java
  src/main/java/com/parley/parley/models/Instructor.java
  src/main/java/com/parley/parley/models/Student.java
  src/main/java/com/parley/parley/repository/StudentRepository.java
  src/main/resources/templates/login.html
Labels: bug, enhancement, refactor

#28 Rob monday
  src/main/java/com/parley/parley/controllers/dummyController.java
Labels: enhancement

#30 Fritts
  README.md
  docs/TeamAgreement.md
  docs/UserStories.md
  src/main/java/com/parley/parley/ParleyApplication.java
  src/main/java/com/parley/parley/UserDetailsServiceImplementation.java
  src/main/java/com/parley/parley/config/WebSecurityConfig.java
  src/main/java/com/parley/parley/controllers/InstructorController.java
  src/main/java/com/parley/parley/controllers/UserAccountController.java
  src/main/java/com/parley/parley/controllers/dummyController.java
  src/main/java/com/parley/parley/models/RoleType.java
  src/main/java/com/parley/parley/models/Student.java
  src/main/java/com/parley/parley/models/UserAccount.java
  src/main/java/com/parley/parley/repository/InstructorRepository.java
  src/main/java/com/parley/parley/repository/StudentRepository.java
  src/main/java/com/parley/parley/repository/UserAccountRepository.java
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/reset.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/loggedInHeader.html
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/makeAdmin.html
  src/main/resources/templates/myprofile.html
Labels: bug

#31 Rob tuesday
  bin/main/application.properties
  bin/main/static/css/aboutus.css
  bin/main/static/css/bootstrap.min.css
  bin/main/static/css/reset.css
  bin/main/static/images/Luke.png
  bin/main/static/images/Robert.png
  bin/main/static/images/Steve.png
  bin/main/static/images/dry-erase-home.png
  bin/main/static/images/error.jpg
  bin/main/static/images/markerAndEraser.jpg
  bin/main/static/images/will.jpg
  bin/main/templates/aboutus.html
  bin/main/templates/add_prompt.html
  bin/main/templates/error.html
  bin/main/templates/fragments/footer.html
  bin/main/templates/fragments/header.html
  bin/main/templates/fragments/loggedInHeader.html
  bin/main/templates/home.html
  bin/main/templates/instructors.html
  bin/main/templates/login.html
  bin/main/templates/logout_completed.html
  bin/main/templates/makeAdmin.html
  bin/main/templates/myprofile.html
  bin/main/templates/students.html
  src/main/java/com/parley/parley/config/S3Client.java
  src/main/java/com/parley/parley/controllers/DummyController.java
  src/main/java/com/parley/parley/controllers/InstructorController.java
  src/main/java/com/parley/parley/controllers/StudentController.java
  src/main/java/com/parley/parley/controllers/dummyController.java
  src/main/resources/templates/add_prompt.html
  src/main/resources/templates/instructors.html
  src/main/resources/templates/students.html
  src/test/java/com/parley/parley/ParleyApplicationTests.java
Labels: enhancement

#32 fix: removed and conslidated instructor to prompts controller
  src/main/java/com/parley/parley/controllers/InstructorController.java
  src/main/java/com/parley/parley/controllers/PromptsController.java
Labels: bug

#33 Student model lc
  src/main/java/com/parley/parley/config/WebSecurityConfig.java
  src/main/java/com/parley/parley/controllers/evaluationController.java
  src/main/resources/static/css/slider.css
  src/main/resources/static/js/slider.js
  src/main/resources/templates/error.html
  src/main/resources/templates/evaluation.html
Labels: enhancement

#34 feat: added myprofile page, assessments, and fragments
  src/main/java/com/parley/parley/ParleyApplication.java
  src/main/java/com/parley/parley/controllers/UserAccountController.java
  src/main/java/com/parley/parley/models/Prompts.java
  src/main/java/com/parley/parley/models/Schedules.java
  src/main/java/com/parley/parley/models/UserAccount.java
  src/main/resources/templates/fragments/adminheader.html
  src/main/resources/templates/fragments/assessments.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/loggedInHeader.html
  src/main/resources/templates/fragments/schedule.html
  src/main/resources/templates/myassessments.html
  src/main/resources/templates/myprofile.html
Labels: enhancement, refactor

#35 Fritts
  src/main/java/com/parley/parley/config/WebSecurityConfig.java
  src/main/java/com/parley/parley/controllers/UserAccountController.java
  src/main/resources/static/css/general.css
  src/main/resources/static/css/modalOveride.css
  src/main/resources/static/js/disableBackButton.js
  src/main/resources/static/js/modal.js
  src/main/resources/templates/evaluation.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/login.html
  src/main/resources/templates/logout_completed.html
  src/main/resources/templates/makeAdmin.html
Labels: enhancement

#36 Day3
  src/main/java/com/parley/parley/controllers/PromptsController.java
  src/main/resources/static/css/slider.css
  src/main/resources/templates/add_prompt.html
  src/main/resources/templates/evaluation.html
  src/main/resources/templates/logout_completed.html
Labels: refactor

#38 Myprofilepage
  Interview 02 _ common_curriculum.html
  src/main/java/com/parley/parley/controllers/AssessmentsController.java
  src/main/java/com/parley/parley/controllers/UserAccountController.java
  src/main/java/com/parley/parley/controllers/scheduleInterviewController.java
  src/main/java/com/parley/parley/models/Schedules.java
  src/main/java/com/parley/parley/models/UserAccount.java
  src/main/resources/templates/addSchedule.html
  src/main/resources/templates/fragments/schedule.html
  src/main/resources/templates/fragments/scheduledInterviewsFragment.html
  src/main/resources/templates/myprofile.html
Labels: bug, enhancement, refactor
